import React from "react";
import { Link } from "react-router-dom";
const Home = () => {
  return (
    <div className="dhiwise-navigation">
      <h1>Homepage</h1>
      <p className="headline">
        This project was generated By{" "}
        <a href="https://www.dhiwise.com">Dhiwise</a>. Quickly use below links
        to navigate through all pages.
      </p>
      <ul>
        <li>
          <Link to="/">Animatedstartinghomepage</Link>
        </li>
        <li>
          <Link to="/services">Services</Link>
        </li>
        <li>
          <Link to="/aboutus">Aboutus</Link>
        </li>
        <li>
          <Link to="/contactusone">ContactusOne</Link>
        </li>
        <li>
          <Link to="/mainhomepage">Mainhomepage</Link>
        </li>
        <li>
          <Link to="/servicesone">ServicesOne</Link>
        </li>
        <li>
          <Link to="/servicesdigitaldropdown">Servicesdigitaldropdown</Link>
        </li>
        <li>
          <Link to="/servicesonboardingdropdown">
            Servicesonboardingdropdown
          </Link>
        </li>
        <li>
          <Link to="/serviceswebappdropdown">Serviceswebappdropdown</Link>
        </li>
        <li>
          <Link to="/servicestechnicaldeopdown">Servicestechnicaldeopdown</Link>
        </li>
        <li>
          <Link to="/aboutusdefault">Aboutusdefault</Link>
        </li>
        <li>
          <Link to="/aboutusbusinessesdropdown">Aboutusbusinessesdropdown</Link>
        </li>
        <li>
          <Link to="/aboutuseducationalinstitutedropdown">
            Aboutuseducationalinstitutedropdown
          </Link>
        </li>
        <li>
          <Link to="/aboutusnonprofitorganisationsdropdown">
            Aboutusnonprofitorganisationsdropdown
          </Link>
        </li>
        <li>
          <Link to="/contactus">Contactus</Link>
        </li>
        <li>
          <Link to="/homepagenewfive">HomepageNEWFive</Link>
        </li>
        <li>
          <Link to="/headerone">HeaderOne</Link>
        </li>
        <li>
          <Link to="/header">Header</Link>
        </li>
        <li>
          <Link to="/homepagenewsix">HomepageNEWSix</Link>
        </li>
        <li>
          <Link to="/headernew">Headernew</Link>
        </li>
      </ul>
    </div>
  );
};
export default Home;
